/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DefAcceleration"
 * 	found in "DefAcceleration.asn"
 */

#ifndef	_AccelerationSet4Way_H_
#define	_AccelerationSet4Way_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Acceleration.h"
#include "VerticalAcceleration.h"
#include "YawRate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AccelerationSet4Way */
typedef struct AccelerationSet4Way {
	Acceleration_t	 Long;
	Acceleration_t	 lat;
	VerticalAcceleration_t	 vert;
	YawRate_t	 yaw;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AccelerationSet4Way_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AccelerationSet4Way;

#ifdef __cplusplus
}
#endif

#endif	/* _AccelerationSet4Way_H_ */
#include <asn_internal.h>
