/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SPATIntersectionState"
 * 	found in "SPATIntersectionState.asn"
 */

#ifndef	_IntersectionState_H_
#define	_IntersectionState_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NodeReferenceID.h"
#include "IntersectionStatusObject.h"
#include "MinuteOfTheYear.h"
#include "DSecond.h"
#include "PhaseList.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IntersectionState */
typedef struct IntersectionState {
	NodeReferenceID_t	 intersectionId;
	IntersectionStatusObject_t	 status;
	MinuteOfTheYear_t	*moy	/* OPTIONAL */;
	DSecond_t	*timeStamp	/* OPTIONAL */;
	PhaseList_t	 phases;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntersectionState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntersectionState;

#ifdef __cplusplus
}
#endif

#endif	/* _IntersectionState_H_ */
#include <asn_internal.h>
