/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MapLane"
 * 	found in "MapLane.asn"
 */

#ifndef	_LaneList_H_
#define	_LaneList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Lane;

/* LaneList */
typedef struct LaneList {
	A_SEQUENCE_OF(struct Lane) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LaneList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LaneList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Lane.h"

#endif	/* _LaneList_H_ */
#include <asn_internal.h>
