/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MapNode"
 * 	found in "MapNode.asn"
 */

#ifndef	_Node_H_
#define	_Node_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DescriptiveName.h"
#include "NodeReferenceID.h"
#include "Position3D.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LinkList;

/* Node */
typedef struct Node {
	DescriptiveName_t	*name	/* OPTIONAL */;
	NodeReferenceID_t	 id;
	Position3D_t	 refPos;
	struct LinkList	*inLinks	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Node_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Node;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LinkList.h"

#endif	/* _Node_H_ */
#include <asn_internal.h>
