/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM.asn"
 */

#ifndef	_ParticipantType_H_
#define	_ParticipantType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ParticipantType {
	ParticipantType_unknown	= 0,
	ParticipantType_motor	= 1,
	ParticipantType_non_motor	= 2,
	ParticipantType_pedestrian	= 3,
	ParticipantType_rsu	= 4
	/*
	 * Enumeration is extensible
	 */
} e_ParticipantType;

/* ParticipantType */
typedef long	 ParticipantType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParticipantType;
asn_struct_free_f ParticipantType_free;
asn_struct_print_f ParticipantType_print;
asn_constr_check_f ParticipantType_constraint;
ber_type_decoder_f ParticipantType_decode_ber;
der_type_encoder_f ParticipantType_encode_der;
xer_type_decoder_f ParticipantType_decode_xer;
xer_type_encoder_f ParticipantType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _ParticipantType_H_ */
#include <asn_internal.h>
