/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "RSM"
 * 	found in "RSM.asn"
 */

#ifndef	_ParticipantList_H_
#define	_ParticipantList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ParticipantData;

/* ParticipantList */
typedef struct ParticipantList {
	A_SEQUENCE_OF(struct ParticipantData) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ParticipantList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ParticipantList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ParticipantData.h"

#endif	/* _ParticipantList_H_ */
#include <asn_internal.h>
