/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "VehSafetyExt"
 * 	found in "VehSafetyExt.asn"
 */

#include "PathHistoryPoint.h"

static asn_TYPE_member_t asn_MBR_PathHistoryPoint_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PathHistoryPoint, llvOffset),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionOffsetLLV,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"llvOffset"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PathHistoryPoint, timeOffset),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimeOffset,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"timeOffset"
		},
	{ ATF_POINTER, 3, offsetof(struct PathHistoryPoint, speed),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Speed,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"speed"
		},
	{ ATF_POINTER, 2, offsetof(struct PathHistoryPoint, posAccuracy),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositionConfidenceSet,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"posAccuracy"
		},
	{ ATF_POINTER, 1, offsetof(struct PathHistoryPoint, heading),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CoarseHeading,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"heading"
		},
};
static const ber_tlv_tag_t asn_DEF_PathHistoryPoint_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PathHistoryPoint_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* llvOffset */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* timeOffset */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* speed */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* posAccuracy */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* heading */
};
static asn_SEQUENCE_specifics_t asn_SPC_PathHistoryPoint_specs_1 = {
	sizeof(struct PathHistoryPoint),
	offsetof(struct PathHistoryPoint, _asn_ctx),
	asn_MAP_PathHistoryPoint_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* Start extensions */
	6	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PathHistoryPoint = {
	"PathHistoryPoint",
	"PathHistoryPoint",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PathHistoryPoint_tags_1,
	sizeof(asn_DEF_PathHistoryPoint_tags_1)
		/sizeof(asn_DEF_PathHistoryPoint_tags_1[0]), /* 1 */
	asn_DEF_PathHistoryPoint_tags_1,	/* Same as above */
	sizeof(asn_DEF_PathHistoryPoint_tags_1)
		/sizeof(asn_DEF_PathHistoryPoint_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PathHistoryPoint_1,
	5,	/* Elements count */
	&asn_SPC_PathHistoryPoint_specs_1	/* Additional specs */
};

