/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "SPATIntersectionState"
 * 	found in "SPATIntersectionState.asn"
 */

#ifndef	_PhaseStateList_H_
#define	_PhaseStateList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PhaseState;

/* PhaseStateList */
typedef struct PhaseStateList {
	A_SEQUENCE_OF(struct PhaseState) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PhaseStateList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PhaseStateList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PhaseState.h"

#endif	/* _PhaseStateList_H_ */
#include <asn_internal.h>
