/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DefPositionOffset"
 * 	found in "DefPositionOffset.asn"
 */

#ifndef	_PositionOffsetLLV_H_
#define	_PositionOffsetLLV_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PositionOffsetLL.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct VerticalOffset;

/* PositionOffsetLLV */
typedef struct PositionOffsetLLV {
	PositionOffsetLL_t	 offsetLL;
	struct VerticalOffset	*offsetV	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PositionOffsetLLV_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PositionOffsetLLV;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "VerticalOffset.h"

#endif	/* _PositionOffsetLLV_H_ */
#include <asn_internal.h>
