/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "VehSafetyExt"
 * 	found in "VehSafetyExt.asn"
 */

#ifndef	_RadiusOfCurvature_H_
#define	_RadiusOfCurvature_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RadiusOfCurvature */
typedef long	 RadiusOfCurvature_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RadiusOfCurvature;
asn_struct_free_f RadiusOfCurvature_free;
asn_struct_print_f RadiusOfCurvature_print;
asn_constr_check_f RadiusOfCurvature_constraint;
ber_type_decoder_f RadiusOfCurvature_decode_ber;
der_type_encoder_f RadiusOfCurvature_encode_der;
xer_type_decoder_f RadiusOfCurvature_decode_xer;
xer_type_encoder_f RadiusOfCurvature_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RadiusOfCurvature_H_ */
#include <asn_internal.h>
