/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "DefPositionOffset"
 * 	found in "DefPositionOffset.asn"
 */

#ifndef	_VertOffset_B12_H_
#define	_VertOffset_B12_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* VertOffset-B12 */
typedef long	 VertOffset_B12_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VertOffset_B12;
asn_struct_free_f VertOffset_B12_free;
asn_struct_print_f VertOffset_B12_print;
asn_constr_check_f VertOffset_B12_constraint;
ber_type_decoder_f VertOffset_B12_decode_ber;
der_type_encoder_f VertOffset_B12_encode_der;
xer_type_decoder_f VertOffset_B12_decode_xer;
xer_type_encoder_f VertOffset_B12_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _VertOffset_B12_H_ */
#include <asn_internal.h>
